local_costmap:
  
  update_frequency: 1
  publish_frequency: 1
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 4
  height: 5
  origin_x: -1.5
  origin_y: -1.5
  resolution: 0.1
  inflation_radius: 0.6
