// Generated by gencpp from file vrep_common/ForceSensorData.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_FORCESENSORDATA_H
#define VREP_COMMON_MESSAGE_FORCESENSORDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace vrep_common
{
template <class ContainerAllocator>
struct ForceSensorData_
{
  typedef ForceSensorData_<ContainerAllocator> Type;

  ForceSensorData_()
    : sensorState()
    , force()
    , torque()  {
    }
  ForceSensorData_(const ContainerAllocator& _alloc)
    : sensorState(_alloc)
    , force(_alloc)
    , torque(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int32_<ContainerAllocator>  _sensorState_type;
  _sensorState_type sensorState;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _force_type;
  _force_type force;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _torque_type;
  _torque_type torque;





  typedef boost::shared_ptr< ::vrep_common::ForceSensorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::ForceSensorData_<ContainerAllocator> const> ConstPtr;

}; // struct ForceSensorData_

typedef ::vrep_common::ForceSensorData_<std::allocator<void> > ForceSensorData;

typedef boost::shared_ptr< ::vrep_common::ForceSensorData > ForceSensorDataPtr;
typedef boost::shared_ptr< ::vrep_common::ForceSensorData const> ForceSensorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::ForceSensorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::ForceSensorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrep_common::ForceSensorData_<ContainerAllocator1> & lhs, const ::vrep_common::ForceSensorData_<ContainerAllocator2> & rhs)
{
  return lhs.sensorState == rhs.sensorState &&
    lhs.force == rhs.force &&
    lhs.torque == rhs.torque;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrep_common::ForceSensorData_<ContainerAllocator1> & lhs, const ::vrep_common::ForceSensorData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrep_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrep_common::ForceSensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::ForceSensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::ForceSensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::ForceSensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::ForceSensorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::ForceSensorData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::ForceSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "975cc3fe659f11cb0dbd06416cff4a10";
  }

  static const char* value(const ::vrep_common::ForceSensorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x975cc3fe659f11cbULL;
  static const uint64_t static_value2 = 0x0dbd06416cff4a10ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::ForceSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/ForceSensorData";
  }

  static const char* value(const ::vrep_common::ForceSensorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::ForceSensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int32 sensorState\n"
"geometry_msgs/Vector3 force\n"
"geometry_msgs/Vector3 torque\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32\n"
"int32 data\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::vrep_common::ForceSensorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::ForceSensorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensorState);
      stream.next(m.force);
      stream.next(m.torque);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForceSensorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::ForceSensorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrep_common::ForceSensorData_<ContainerAllocator>& v)
  {
    s << indent << "sensorState: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.sensorState);
    s << indent << "force: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
    s << indent << "torque: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.torque);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_FORCESENSORDATA_H
