// Generated by gencpp from file vrep_common/simRosLoadModelRequest.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSLOADMODELREQUEST_H
#define VREP_COMMON_MESSAGE_SIMROSLOADMODELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrep_common
{
template <class ContainerAllocator>
struct simRosLoadModelRequest_
{
  typedef simRosLoadModelRequest_<ContainerAllocator> Type;

  simRosLoadModelRequest_()
    : fileName()  {
    }
  simRosLoadModelRequest_(const ContainerAllocator& _alloc)
    : fileName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fileName_type;
  _fileName_type fileName;





  typedef boost::shared_ptr< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simRosLoadModelRequest_

typedef ::vrep_common::simRosLoadModelRequest_<std::allocator<void> > simRosLoadModelRequest;

typedef boost::shared_ptr< ::vrep_common::simRosLoadModelRequest > simRosLoadModelRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosLoadModelRequest const> simRosLoadModelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrep_common::simRosLoadModelRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosLoadModelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.fileName == rhs.fileName;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrep_common::simRosLoadModelRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosLoadModelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrep_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c96d4662a80949a4927729271153923";
  }

  static const char* value(const ::vrep_common::simRosLoadModelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c96d4662a80949aULL;
  static const uint64_t static_value2 = 0x4927729271153923ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/simRosLoadModelRequest";
  }

  static const char* value(const ::vrep_common::simRosLoadModelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# simxInt simxLoadModel(const simxChar* modelPathAndName,simxChar options,simxInt* baseHandle,simxInt operationMode)\n"
"#\n"
"\n"
"string fileName\n"
;
  }

  static const char* value(const ::vrep_common::simRosLoadModelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fileName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosLoadModelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::simRosLoadModelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrep_common::simRosLoadModelRequest_<ContainerAllocator>& v)
  {
    s << indent << "fileName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fileName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSLOADMODELREQUEST_H
