// Generated by gencpp from file vrep_common/simRosGetCollisionHandleRequest.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETCOLLISIONHANDLEREQUEST_H
#define VREP_COMMON_MESSAGE_SIMROSGETCOLLISIONHANDLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrep_common
{
template <class ContainerAllocator>
struct simRosGetCollisionHandleRequest_
{
  typedef simRosGetCollisionHandleRequest_<ContainerAllocator> Type;

  simRosGetCollisionHandleRequest_()
    : collisionName()  {
    }
  simRosGetCollisionHandleRequest_(const ContainerAllocator& _alloc)
    : collisionName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _collisionName_type;
  _collisionName_type collisionName;





  typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simRosGetCollisionHandleRequest_

typedef ::vrep_common::simRosGetCollisionHandleRequest_<std::allocator<void> > simRosGetCollisionHandleRequest;

typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleRequest > simRosGetCollisionHandleRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleRequest const> simRosGetCollisionHandleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.collisionName == rhs.collisionName;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrep_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf86508d9f797a77ca9b0cab99fc61ca";
  }

  static const char* value(const ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf86508d9f797a77ULL;
  static const uint64_t static_value2 = 0xca9b0cab99fc61caULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/simRosGetCollisionHandleRequest";
  }

  static const char* value(const ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# simInt simGetCollisionHandle(const simChar* collisionObjectName)\n"
"#\n"
"\n"
"string collisionName\n"
;
  }

  static const char* value(const ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collisionName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosGetCollisionHandleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator>& v)
  {
    s << indent << "collisionName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.collisionName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETCOLLISIONHANDLEREQUEST_H
