// Generated by gencpp from file vrep_common/simRosGetStringParameterRequest.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETSTRINGPARAMETERREQUEST_H
#define VREP_COMMON_MESSAGE_SIMROSGETSTRINGPARAMETERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrep_common
{
template <class ContainerAllocator>
struct simRosGetStringParameterRequest_
{
  typedef simRosGetStringParameterRequest_<ContainerAllocator> Type;

  simRosGetStringParameterRequest_()
    : parameter(0)  {
    }
  simRosGetStringParameterRequest_(const ContainerAllocator& _alloc)
    : parameter(0)  {
  (void)_alloc;
    }



   typedef int32_t _parameter_type;
  _parameter_type parameter;





  typedef boost::shared_ptr< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simRosGetStringParameterRequest_

typedef ::vrep_common::simRosGetStringParameterRequest_<std::allocator<void> > simRosGetStringParameterRequest;

typedef boost::shared_ptr< ::vrep_common::simRosGetStringParameterRequest > simRosGetStringParameterRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosGetStringParameterRequest const> simRosGetStringParameterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.parameter == rhs.parameter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrep_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b5e34835331aac7a9065c5abd204e3b";
  }

  static const char* value(const ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b5e34835331aac7ULL;
  static const uint64_t static_value2 = 0xa9065c5abd204e3bULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/simRosGetStringParameterRequest";
  }

  static const char* value(const ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# simChar* simGetStringParameter(simInt parameter)\n"
"#\n"
"\n"
"int32 parameter\n"
;
  }

  static const char* value(const ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.parameter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosGetStringParameterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrep_common::simRosGetStringParameterRequest_<ContainerAllocator>& v)
  {
    s << indent << "parameter: ";
    Printer<int32_t>::stream(s, indent + "  ", v.parameter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETSTRINGPARAMETERREQUEST_H
