// Generated by gencpp from file vrep_common/simRosDisableSubscriberRequest.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSDISABLESUBSCRIBERREQUEST_H
#define VREP_COMMON_MESSAGE_SIMROSDISABLESUBSCRIBERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrep_common
{
template <class ContainerAllocator>
struct simRosDisableSubscriberRequest_
{
  typedef simRosDisableSubscriberRequest_<ContainerAllocator> Type;

  simRosDisableSubscriberRequest_()
    : subscriberID(0)  {
    }
  simRosDisableSubscriberRequest_(const ContainerAllocator& _alloc)
    : subscriberID(0)  {
  (void)_alloc;
    }



   typedef int32_t _subscriberID_type;
  _subscriberID_type subscriberID;





  typedef boost::shared_ptr< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simRosDisableSubscriberRequest_

typedef ::vrep_common::simRosDisableSubscriberRequest_<std::allocator<void> > simRosDisableSubscriberRequest;

typedef boost::shared_ptr< ::vrep_common::simRosDisableSubscriberRequest > simRosDisableSubscriberRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosDisableSubscriberRequest const> simRosDisableSubscriberRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator2> & rhs)
{
  return lhs.subscriberID == rhs.subscriberID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrep_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62d69ecf284a2ca70f446f9db0533ca8";
  }

  static const char* value(const ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62d69ecf284a2ca7ULL;
  static const uint64_t static_value2 = 0x0f446f9db0533ca8ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/simRosDisableSubscriberRequest";
  }

  static const char* value(const ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"#\n"
"#\n"
"\n"
"int32 subscriberID\n"
;
  }

  static const char* value(const ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.subscriberID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosDisableSubscriberRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrep_common::simRosDisableSubscriberRequest_<ContainerAllocator>& v)
  {
    s << indent << "subscriberID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.subscriberID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSDISABLESUBSCRIBERREQUEST_H
