// Generated by gencpp from file vrep_common/simRosGetObjectHandleRequest.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETOBJECTHANDLEREQUEST_H
#define VREP_COMMON_MESSAGE_SIMROSGETOBJECTHANDLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrep_common
{
template <class ContainerAllocator>
struct simRosGetObjectHandleRequest_
{
  typedef simRosGetObjectHandleRequest_<ContainerAllocator> Type;

  simRosGetObjectHandleRequest_()
    : objectName()  {
    }
  simRosGetObjectHandleRequest_(const ContainerAllocator& _alloc)
    : objectName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _objectName_type;
  _objectName_type objectName;





  typedef boost::shared_ptr< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simRosGetObjectHandleRequest_

typedef ::vrep_common::simRosGetObjectHandleRequest_<std::allocator<void> > simRosGetObjectHandleRequest;

typedef boost::shared_ptr< ::vrep_common::simRosGetObjectHandleRequest > simRosGetObjectHandleRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosGetObjectHandleRequest const> simRosGetObjectHandleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.objectName == rhs.objectName;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrep_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d6700ec420d7f32e8dc7b117e3b8b51";
  }

  static const char* value(const ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d6700ec420d7f32ULL;
  static const uint64_t static_value2 = 0xe8dc7b117e3b8b51ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/simRosGetObjectHandleRequest";
  }

  static const char* value(const ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# simInt simGetObjectHandle(const simChar* objectName)\n"
"#\n"
"\n"
"string objectName\n"
;
  }

  static const char* value(const ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objectName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosGetObjectHandleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrep_common::simRosGetObjectHandleRequest_<ContainerAllocator>& v)
  {
    s << indent << "objectName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.objectName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETOBJECTHANDLEREQUEST_H
