// Generated by gencpp from file vrep_common/simRosEnablePublisherResponse.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSENABLEPUBLISHERRESPONSE_H
#define VREP_COMMON_MESSAGE_SIMROSENABLEPUBLISHERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrep_common
{
template <class ContainerAllocator>
struct simRosEnablePublisherResponse_
{
  typedef simRosEnablePublisherResponse_<ContainerAllocator> Type;

  simRosEnablePublisherResponse_()
    : effectiveTopicName()  {
    }
  simRosEnablePublisherResponse_(const ContainerAllocator& _alloc)
    : effectiveTopicName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _effectiveTopicName_type;
  _effectiveTopicName_type effectiveTopicName;





  typedef boost::shared_ptr< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simRosEnablePublisherResponse_

typedef ::vrep_common::simRosEnablePublisherResponse_<std::allocator<void> > simRosEnablePublisherResponse;

typedef boost::shared_ptr< ::vrep_common::simRosEnablePublisherResponse > simRosEnablePublisherResponsePtr;
typedef boost::shared_ptr< ::vrep_common::simRosEnablePublisherResponse const> simRosEnablePublisherResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator1> & lhs, const ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator2> & rhs)
{
  return lhs.effectiveTopicName == rhs.effectiveTopicName;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator1> & lhs, const ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrep_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8280ce6c5ec203a92c1559486bea2e2e";
  }

  static const char* value(const ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8280ce6c5ec203a9ULL;
  static const uint64_t static_value2 = 0x2c1559486bea2e2eULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/simRosEnablePublisherResponse";
  }

  static const char* value(const ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string effectiveTopicName\n"
"\n"
;
  }

  static const char* value(const ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.effectiveTopicName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosEnablePublisherResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrep_common::simRosEnablePublisherResponse_<ContainerAllocator>& v)
  {
    s << indent << "effectiveTopicName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.effectiveTopicName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSENABLEPUBLISHERRESPONSE_H
