// Generated by gencpp from file vrep_common/simRosDisableSubscriberResponse.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSDISABLESUBSCRIBERRESPONSE_H
#define VREP_COMMON_MESSAGE_SIMROSDISABLESUBSCRIBERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrep_common
{
template <class ContainerAllocator>
struct simRosDisableSubscriberResponse_
{
  typedef simRosDisableSubscriberResponse_<ContainerAllocator> Type;

  simRosDisableSubscriberResponse_()
    : result(0)  {
    }
  simRosDisableSubscriberResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simRosDisableSubscriberResponse_

typedef ::vrep_common::simRosDisableSubscriberResponse_<std::allocator<void> > simRosDisableSubscriberResponse;

typedef boost::shared_ptr< ::vrep_common::simRosDisableSubscriberResponse > simRosDisableSubscriberResponsePtr;
typedef boost::shared_ptr< ::vrep_common::simRosDisableSubscriberResponse const> simRosDisableSubscriberResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator1> & lhs, const ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator1> & lhs, const ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrep_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25458147911545c320c4c0a299eff763";
  }

  static const char* value(const ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25458147911545c3ULL;
  static const uint64_t static_value2 = 0x20c4c0a299eff763ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/simRosDisableSubscriberResponse";
  }

  static const char* value(const ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 result\n"
"\n"
;
  }

  static const char* value(const ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosDisableSubscriberResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrep_common::simRosDisableSubscriberResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSDISABLESUBSCRIBERRESPONSE_H
