// Generated by gencpp from file vrep_common/simRosSynchronousRequest.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSSYNCHRONOUSREQUEST_H
#define VREP_COMMON_MESSAGE_SIMROSSYNCHRONOUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrep_common
{
template <class ContainerAllocator>
struct simRosSynchronousRequest_
{
  typedef simRosSynchronousRequest_<ContainerAllocator> Type;

  simRosSynchronousRequest_()
    : enable(0)  {
    }
  simRosSynchronousRequest_(const ContainerAllocator& _alloc)
    : enable(0)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_type;
  _enable_type enable;





  typedef boost::shared_ptr< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simRosSynchronousRequest_

typedef ::vrep_common::simRosSynchronousRequest_<std::allocator<void> > simRosSynchronousRequest;

typedef boost::shared_ptr< ::vrep_common::simRosSynchronousRequest > simRosSynchronousRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosSynchronousRequest const> simRosSynchronousRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vrep_common::simRosSynchronousRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosSynchronousRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vrep_common::simRosSynchronousRequest_<ContainerAllocator1> & lhs, const ::vrep_common::simRosSynchronousRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vrep_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34abd7794638063ef7576ad13e0da876";
  }

  static const char* value(const ::vrep_common::simRosSynchronousRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34abd7794638063eULL;
  static const uint64_t static_value2 = 0xf7576ad13e0da876ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/simRosSynchronousRequest";
  }

  static const char* value(const ::vrep_common::simRosSynchronousRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# simxInt simxSynchronous(simxChar enable)\n"
"#\n"
"\n"
"uint8 enable\n"
;
  }

  static const char* value(const ::vrep_common::simRosSynchronousRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosSynchronousRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrep_common::simRosSynchronousRequest_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSSYNCHRONOUSREQUEST_H
