// Generated by gencpp from file vrep_common/simRosGetLastErrorsRequest.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETLASTERRORSREQUEST_H
#define VREP_COMMON_MESSAGE_SIMROSGETLASTERRORSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrep_common
{
template <class ContainerAllocator>
struct simRosGetLastErrorsRequest_
{
  typedef simRosGetLastErrorsRequest_<ContainerAllocator> Type;

  simRosGetLastErrorsRequest_()
    {
    }
  simRosGetLastErrorsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simRosGetLastErrorsRequest_

typedef ::vrep_common::simRosGetLastErrorsRequest_<std::allocator<void> > simRosGetLastErrorsRequest;

typedef boost::shared_ptr< ::vrep_common::simRosGetLastErrorsRequest > simRosGetLastErrorsRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosGetLastErrorsRequest const> simRosGetLastErrorsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace vrep_common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/simRosGetLastErrorsRequest";
  }

  static const char* value(const ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#\n"
"# simxInt simxGetLastErrors(simxInt* errorCnt,simxChar** errorStrings,simxInt operationMode)\n"
"#\n"
"\n"
"\n"
;
  }

  static const char* value(const ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosGetLastErrorsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::vrep_common::simRosGetLastErrorsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETLASTERRORSREQUEST_H
